sudo: required

language: bash

services:
    - docker

before_install:
    - docker build -t hgi/cookie-monster/tests -f docker/test/dind/Dockerfile .

script:
    - docker run --privileged hgi/cookie-monster/tests
