SPECIFIC_QUERY_ALIAS = "updates"

UPDATE_DATA_OBJECT_NAME_PROPERTY = "dataName"
UPDATE_COLLECTION_NAME_PROPERTY = "collName"
UPDATE_DATA_TIMESTAMP_PROPERTY = "dataModifyTimestamp"
UPDATE_METADATA_TIMESTAMP_PROPERTY = "dataModifyTimestamp"
UPDATE_METADATA_ATTRIBUTE_NAME_PROPERTY = "metaAttrName"
UPDATE_METADATA_ATTRIBUTE_VALUE_PROPERTY = "metaAttrValue"
UPDATE_HASH_PROPERTY = "dataChecksum"
