DATA_UPDATES_QUERY_ALIAS = "dataUpdates"
METADATA_UPDATES_QUERY_ALIAS = "metadataUpdates"

UPDATE_COLLECTION_NAME_PROPERTY = "collectionName"

UPDATE_DATA_OBJECT_NAME_PROPERTY = "dataName"
UPDATE_DATA_ID = "dataID"
UPDATE_DATA_REPLICA_NUMBER = "dataReplicaNumber"
UPDATE_DATA_HASH_PROPERTY = "dataChecksum"
UPDATE_DATA_TIMESTAMP_PROPERTY = "dataModifyTimestamp"
UPDATE_DATA_REPLICA_STATUS = "dataReplicaStatus"

UPDATE_METADATA_TIMESTAMP_PROPERTY = "metadataModifyTimestamp"
UPDATE_METADATA_ATTRIBUTE_NAME_PROPERTY = "metadataAttrName"
UPDATE_METADATA_ATTRIBUTE_VALUE_PROPERTY = "metadataAttrValue"

