MODIFIED_DATA_QUERY_ALIAS = "dataModifiedPartial"
MODIFIED_METADATA_QUERY_ALIAS = "metadataModifiedPartial"

MODIFIED_COLLECTION_NAME_PROPERTY = "coll_name"

MODIFIED_DATA_NAME_PROPERTY = "data_name"
MODIFIED_DATA_ID_PROPERTY = "data_id"
MODIFIED_DATA_REPLICA_NUMBER_PROPERTY = "data_repl_num"
MODIFIED_DATA_REPLICA_CHECKSUM_PROPERTY = "data_checksum"
MODIFIED_DATA_TIMESTAMP_PROPERTY = "data_modify_ts"
MODIFIED_DATA_REPLICA_STATUS_PROPERTY = "data_repl_status"

MODIFIED_METADATA_ATTRIBUTE_NAME_PROPERTY = "meta_attr_name"
MODIFIED_METADATA_ATTRIBUTE_VALUE_PROPERTY = "meta_attr_value"
MODIFIED_METADATA_TIMESTAMP_PROPERTY = "meta_modify_ts"
